dist: trusty
language: node_js
node_js: '6'

cache:
    directories:
        - node_modules
        - /home/travis/.sonar/cache

addons:
    sonarqube:
        branches:
            - .*
        token: $SONAR_AUTH_TOKEN
        github_token: $GITHUB_ACCESS_TOKEN

install:
    - npm install

before_script:
    - chmod +x scripts/sonarqube.sh

script:
    - scripts/sonarqube.sh
    - npm build

notifications:
    email: false
